spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  #sql:
    #nit:
      #mode: always # Ensures that Spring Boot initializes the database at startup
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_OAUTH_CLIENT_ID}
            client-secret: ${SPRING_OAUTH_CLIENT_SECRET}
            scope: profile, email
